In [1]:
import pandas as pd
import numpy as np
import os
from os import listdir
import glob
from glob import glob
from os.path import isfile, join
import shutil
import PIL
from PIL import Image
import random
import scipy as sp
from scipy import stats
import seaborn as sns
from matplotlib import pyplot as plt

In [12]:
#find file 
#df_dir = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/contingentproject/EmoInf_consolidation/Khanh/master_results.csv') ##Khanh's project
df_dir = pd.read_csv('/Users/ayesh/Desktop/Gradstuff/contingentproject/EmoInf_consolidation/CMA_data/summarized_pt/master_results.csv') ##my CMA

In [4]:
shrt_df = pd.melt(df_dir, id_vars=['Participant'], value_vars=['BCneuAcc', 'BCfearAcc', 'XYneuAcc', 'XYfearAcc'], var_name='condition', value_name='Total_acc')
shrt_df

     Participant  condition  Total_acc
0              2   BCneuAcc   0.684211
1              3   BCneuAcc   0.555556
2              4   BCneuAcc   0.800000
3              5   BCneuAcc   0.760000
4              6   BCneuAcc   1.000000
..           ...        ...        ...
147           35  XYfearAcc   0.320000
148           36  XYfearAcc   0.880000
149           37  XYfearAcc   0.500000
150           39  XYfearAcc   0.869565
151           40  XYfearAcc   0.590909

[152 rows x 3 columns]

In [5]:
shrt_df.loc[shrt_df['condition'] == 'BCneuAcc', 'valence'] = 'c-neutral'
shrt_df.loc[shrt_df['condition'] == 'BCfearAcc', 'valence'] = 'fearful'

shrt_df.loc[shrt_df['condition'] == 'XYneuAcc', 'valence'] = 'c-neutral'
shrt_df.loc[shrt_df['condition'] == 'XYfearAcc', 'valence'] = 'fearful'

shrt_df.loc[shrt_df['condition'] == 'BCneuAcc', 'Test'] = 'BC'
shrt_df.loc[shrt_df['condition'] == 'BCfearAcc', 'Test'] = 'BC'

shrt_df.loc[shrt_df['condition'] == 'XYneuAcc', 'Test'] = 'XY'
shrt_df.loc[shrt_df['condition'] == 'XYfearAcc', 'Test'] = 'XY'

In [6]:
shrt_df.to_csv('/Users/ayesh/Desktop/Gradstuff/contingentproject/EmoInf_consolidation/CMA_data/CMA-analysis/CMAanova_BCXY.csv')

## 2nd day anova

In [13]:
shrt2_df = pd.melt(df_dir, id_vars=['Participant'], value_vars=['dBCneuAcc', 'dBCfearAcc', 'dXYneuAcc', 'dXYfearAcc'], var_name='condition', value_name='Total_acc')
shrt2_df

     Participant   condition  Total_acc
0              2   dABneuAcc   0.666667
1              3   dABneuAcc   0.708333
2              4   dABneuAcc   1.000000
3              5   dABneuAcc   1.000000
4              6   dABneuAcc   1.000000
..           ...         ...        ...
223           35  dXYfearAcc   0.320000
224           36  dXYfearAcc   0.680000
225           37  dXYfearAcc   0.375000
226           39  dXYfearAcc   0.739130
227           40  dXYfearAcc   0.636364

[228 rows x 3 columns]

In [14]:
shrt2_df.loc[shrt2_df['condition'] == 'dBCneuAcc', 'valence'] = 'c-neutral'
shrt2_df.loc[shrt2_df['condition'] == 'dBCfearAcc', 'valence'] = 'fearful'

shrt2_df.loc[shrt2_df['condition'] == 'dXYneuAcc', 'valence'] = 'c-neutral'
shrt2_df.loc[shrt2_df['condition'] == 'dXYfearAcc', 'valence'] = 'fearful'

shrt2_df.loc[shrt2_df['condition'] == 'dBCneuAcc', 'Test'] = 'BC'
shrt2_df.loc[shrt2_df['condition'] == 'dBCfearAcc', 'Test'] = 'BC'

shrt2_df.loc[shrt2_df['condition'] == 'dXYneuAcc', 'Test'] = 'XY'
shrt2_df.loc[shrt2_df['condition'] == 'dXYfearAcc', 'Test'] = 'XY'

In [15]:
shrt2_df.to_csv('/Users/ayesh/Desktop/Gradstuff/contingentproject/EmoInf_consolidation/CMA_data/CMA-analysis/CMAanova2_BCXY2.csv')